apiVersion: v1
kind: Secret
metadata:
  name: dremio-tls
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tXG5GQUtFX0NFUlRfQ09OVEVOVFxuLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5GQUtFX0tFWV9DT05URU5UXG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
