
apiVersion: v1
kind: Secret
metadata:
  name: dremio-tls
  namespace: default
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURkLi4uPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcC4uLj09Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
